application: mapreduce-pycon
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:

- url: /.*
  script: urls.py

inbound_services:
- warmup

includes:
- mapreduce/include.yaml